project:
  type: website

website:
  title: "Happiness"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project_proposal.qmd
        text: "Project Proposal (deadline: June 8th 2026)"
      - href: about.qmd
        text: "about this site"


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

